import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const OutfitFont = Outfit({
  subsets: ["latin"],
});
// english alph(latin), greek, arabic, bengali



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${OutfitFont.className} h-full antialiased`}>
      <body className="m-0 p-0 w-full">
        <Navbar />

        {/* ❌ max-w-7xl removed from main */}
        <main className="w-full">{children}</main>

        <Footer />
      </body>
    </html>
  );
}